"""
SurakshaPath AI — Fault & Anomaly Injector Framework.

Provides an independent framework for injecting sensor faults, communication failures,
battery drain, and false alarms without mutating base physics simulation logic.

Supported Fault Types:
  - STUCK_TEMPERATURE: Sensor temperature reading freezes at a static value.
  - STUCK_SMOKE: Sensor smoke reading freezes at a static value.
  - DEAD_NODE: Node health changes to OFFLINE or FAULT, communication health TIMEDOUT.
  - COMM_DEGRADED: Communication health changes to DEGRADED.
  - BATTERY_DRAIN: Battery level rapidly drops to low/zero.
  - FALSE_POSITIVE_FLAME: Flame sensor trips False even without fire.
  - FALSE_NEGATIVE_FLAME: Flame sensor reports False even during active fire.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Set

from communication.packet_schema import (
    TelemetryPacket,
    HEALTH_FAULT,
    HEALTH_OFFLINE,
    HEALTH_DEGRADED,
    HEALTH_TIMEDOUT,
)


@dataclass
class ActiveFault:
    """An active fault injection rule targeting a specific zone or node.

    Attributes:
        fault_type:    Name of the fault (e.g., "STUCK_TEMPERATURE", "DEAD_NODE").
        zone_id:       Target zone identifier.
        start_tick:    Simulation tick when fault becomes active.
        end_tick:      Optional tick when fault automatically expires (None = indefinite).
        value:         Optional numeric/boolean override value (e.g. frozen temperature).
    """
    fault_type: str
    zone_id: str
    start_tick: int = 0
    end_tick: Optional[int] = None
    value: Optional[float] = None


class FaultInjector:
    """Manages scheduled fault injection rules and applies them to TelemetryPackets."""

    def __init__(self) -> None:
        """Initialize FaultInjector with an empty set of fault rules."""
        self._faults: List[ActiveFault] = []

    def add_fault(
        self,
        fault_type: str,
        zone_id: str,
        start_tick: int = 0,
        end_tick: Optional[int] = None,
        value: Optional[float] = None,
    ) -> ActiveFault:
        """Register a new fault injection rule.

        Args:
            fault_type: Type of fault (e.g., "DEAD_NODE", "STUCK_TEMPERATURE").
            zone_id: Target zone ID.
            start_tick: Activation tick.
            end_tick: Expiration tick (None = indefinite).
            value: Optional parameter override value.

        Returns:
            The created ActiveFault object.
        """
        fault = ActiveFault(
            fault_type=fault_type,
            zone_id=zone_id,
            start_tick=start_tick,
            end_tick=end_tick,
            value=value,
        )
        self._faults.append(fault)
        return fault

    def clear_faults(self) -> None:
        """Remove all active fault injection rules."""
        self._faults.clear()

    def get_active_faults(self, current_tick: int) -> List[ActiveFault]:
        """Return list of faults that are active at the given tick."""
        active = []
        for f in self._faults:
            if f.start_tick <= current_tick:
                if f.end_tick is None or current_tick <= f.end_tick:
                    active.append(f)
        return active

    def apply_faults(
        self,
        packets: Dict[str, TelemetryPacket],
        current_tick: int,
    ) -> Dict[str, TelemetryPacket]:
        """Apply active fault injection rules to a dictionary of TelemetryPackets.

        Args:
            packets: Dict of zone_id -> TelemetryPacket generated by SensorGenerator.
            current_tick: Current simulation tick number.

        Returns:
            Dict of zone_id -> mutated TelemetryPacket.
        """
        active_faults = self.get_active_faults(current_tick)
        if not active_faults:
            return packets

        # Process each fault on matching packet
        for fault in active_faults:
            if fault.zone_id not in packets:
                continue

            pkt = packets[fault.zone_id]

            if fault.fault_type == "STUCK_TEMPERATURE":
                stuck_val = fault.value if fault.value is not None else 85.0
                pkt.temperature = stuck_val

            elif fault.fault_type == "STUCK_SMOKE":
                stuck_val = fault.value if fault.value is not None else 0.90
                pkt.smoke_level = max(0.0, min(1.0, stuck_val))

            elif fault.fault_type == "DEAD_NODE":
                pkt.node_health = HEALTH_OFFLINE
                pkt.communication_health = HEALTH_TIMEDOUT
                pkt.firmware_health = HEALTH_FAULT

            elif fault.fault_type == "COMM_DEGRADED":
                pkt.communication_health = HEALTH_DEGRADED

            elif fault.fault_type == "BATTERY_DRAIN":
                drain_val = fault.value if fault.value is not None else 5.0
                pkt.battery_level = max(0.0, drain_val)

            elif fault.fault_type == "FALSE_POSITIVE_FLAME":
                pkt.flame_detected = True

            elif fault.fault_type == "FALSE_NEGATIVE_FLAME":
                pkt.flame_detected = False

            # Append annotation to packet metadata
            pkt.metadata["injected_fault"] = fault.fault_type

        return packets
